In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('../data/raw/data.parquet')

In [6]:
df.head()

,truth_HT_tracks,truth_HT_tracks_2GeV,truth_HT_tracks_5GeV,truth_HT_tracks_10GeV,truth_pT_track1,truth_pT_track2,truth_pT_track3p_r1,truth_pT_track_r1,truth_pT_track_r2,truth_pT_track_r3,...,weights_theoryPDF,weights_theoryAlphaS,weights_theoryPSsoft,weights_theoryPSjet,weights_theoryMPI,weights_theoryPSscale,weights_topBackground,weights_nonstrongDiboson,weights_nonstrongEW,target_dd
0,395.015503,379.750519,339.016571,291.702271,43.137352,39.472950,23.505688,17.155613,1.035230,0.590752,...,0.000047,0.000054,0.000062,0.000051,0.000056,0.000060,0.000056,0.000067,0.000050,0.000012
1,298.974335,276.244202,252.651077,241.618103,124.107307,107.218437,2.099513,1.065130,3.783245,10.292356,...,0.000010,0.000010,0.000011,0.000010,0.000011,0.000013,0.000011,0.000013,0.000010,0.000028
2,579.767883,556.855652,491.024078,466.301941,201.965652,44.236809,0.945035,1.438853,1.261809,4.189490,...,0.000063,0.000067,0.000072,0.000059,0.000062,0.000080,0.000061,0.000072,0.000061,0.000028
3,313.115967,279.098602,241.805145,209.315384,119.625839,54.612926,1.024166,0.749323,0.576291,0.780302,...,0.000009,0.000010,0.000010,0.000009,0.000009,0.000012,0.000009,0.000011,0.000009,0.000005
4,588.024658,551.901855,522.104065,494.843262,94.890800,80.814285,6.141286,1.496324,0.565523,7.133419,...,0.000010,0.000010,0.000011,0.000010,0.000010,0.000014,0.000010,0.000012,0.000011,0.000012

In [4]:
df.describe()

,truth_HT_tracks,truth_HT_tracks_2GeV,truth_HT_tracks_5GeV,truth_HT_tracks_10GeV,truth_pT_track1,truth_pT_track2,truth_pT_track3p_r1,truth_pT_track_r1,truth_pT_track_r2,truth_pT_track_r3,...,weights_theoryPDF,weights_theoryAlphaS,weights_theoryPSsoft,weights_theoryPSjet,weights_theoryMPI,weights_theoryPSscale,weights_topBackground,weights_nonstrongDiboson,weights_nonstrongEW,target_dd
count,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,...,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06,1.035835e+06
mean,3.498906e+02,3.058959e+02,2.686213e+02,2.334444e+02,8.261674e+01,4.382557e+01,3.348121e+00,5.410682e+00,5.405564e+00,5.414434e+00,...,1.729227e-03,1.728798e-03,1.729044e-03,1.728960e-03,1.729302e-03,1.728928e-03,1.728994e-03,1.729243e-03,1.729043e-03,1.728994e-03
std,2.435034e+02,2.395352e+02,2.323787e+02,2.228864e+02,7.622245e+01,3.860418e+01,7.231087e+00,1.724639e+01,1.725892e+01,1.705141e+01,...,3.794506e-03,3.758336e-03,3.824525e-03,3.764809e-03,3.768147e-03,3.731836e-03,3.756053e-03,3.734673e-03,3.769616e-03,2.407164e-03
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-9.900000e+01,-9.900000e+01,-9.900000e+01,-9.900000e+01,-9.900000e+01,-9.900000e+01,...,4.087155e-08,4.024878e-08,4.031832e-08,4.406216e-08,4.092382e-08,0.000000e+00,4.501071e-08,5.430530e-08,4.266466e-08,4.145922e-08
25%,2.019877e+02,1.611692e+02,1.289116e+02,9.954451e+01,3.575342e+01,2.046019e+01,7.490421e-01,7.612877e-01,7.618900e-01,7.614597e-01,...,1.956782e-04,1.989881e-04,1.966149e-04,1.990140e-04,1.976434e-04,2.045431e-04,1.977412e-04,2.054454e-04,1.995492e-04,2.574070e-04
50%,2.859917e+02,2.404851e+02,2.044825e+02,1.719104e+02,6.047155e+01,3.315714e+01,1.235206e+00,1.289049e+00,1.291948e+00,1.293951e+00,...,6.113686e-04,6.180597e-04,6.131956e-04,6.179792e-04,6.141249e-04,6.220824e-04,6.162929e-04,6.271994e-04,6.198257e-04,8.951451e-04
75%,4.211189e+02,3.728638e+02,3.305929e+02,2.903817e+02,1.030367e+02,5.420450e+01,2.758072e+00,3.160772e+00,3.158887e+00,3.163355e+00,...,1.739386e-03,1.746938e-03,1.736983e-03,1.746569e-03,1.742685e-03,1.749298e-03,1.746999e-03,1.754421e-03,1.750135e-03,2.240632e-03
max,5.356273e+03,5.305486e+03,5.270161e+03,5.246536e+03,2.088941e+03,1.453977e+03,4.409968e+02,1.008576e+03,1.336895e+03,1.336895e+03,...,2.218852e-01,2.230839e-01,2.598007e-01,2.371684e-01,2.350881e-01,2.252376e-01,2.382607e-01,2.407133e-01,2.384177e-01,1.334388e-01